FROM python:3.11.5-slim-bullseye

ENV PYTHONBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /  

COPY requirements.txt /  

RUN pip install -r requirements.txt 

COPY . /  

ENTRYPOINT ["sh","-c","./start.sh"] 
